package gaming_café_management_system;

import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import data_access_object.userDAO;
import java.util.Iterator;
import javax.swing.table.TableModel;
import model.User;

public class ManageUsers extends javax.swing.JFrame {

    public ManageUsers() {
        initComponents();
    }

    public void getAllRecords(String email) {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        ArrayList<User> list = userDAO.getAllRecords(email);
        Iterator<User> itr = list.iterator();
        while (itr.hasNext()) {
            User userObj = itr.next();
            if (!userObj.getEmail().equals("admin@gmail.com")) {
                // Fixed the missing parenthesis in the addRow method
                dtm.addRow(new Object[]{userObj.getId(), userObj.getName(), userObj.getEmail(), userObj.getPhone(), userObj.getStatus()});
            }
        }
    }

    private void verifyAndUpdateUserStatus() {
        // Get the selected row index
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow != -1) {
            // Retrieve email and status from the selected row
            TableModel model = jTable1.getModel();
            String email = model.getValueAt(selectedRow, 2).toString();
            String currentStatus = model.getValueAt(selectedRow, 4).toString();

            // Toggle status
            String newStatus = currentStatus.equals("true") ? "false" : "true";

            // Confirm the status change
            int confirmation = JOptionPane.showConfirmDialog(null,
                    "Do you want to change the status of " + email + " to " + newStatus + "?",
                    "Confirm Status Change",
                    JOptionPane.YES_NO_OPTION);

            if (confirmation == JOptionPane.YES_OPTION) {
                // Update the status in the database
                userDAO.changeStatus(email, newStatus);

                // Refresh the table
                getAllRecords("");
            }
        } else {
            // Show a message if no row is selected
            JOptionPane.showMessageDialog(null, "Please select a user to verify!");
        }
    }

    private void showHelpDialog() {
        // HTML content for the help dialog with bold IDs
        String message = "<html>"
                + "<p>Hilal (<b>001</b>)</p>"
                + "<p>Raza (<b>019</b>)</p>"
                + "<p>Qasim (<b>033</b>)</p>"
                + "</html>";

        // Load the help icon image from the specified file path
        ImageIcon icon = new ImageIcon("src/images/help-60.png");

        // Show the message dialog with the formatted HTML and icon
        JOptionPane.showMessageDialog(this, message, "Help", JOptionPane.INFORMATION_MESSAGE, icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonLogout = new javax.swing.JButton();
        buttonVerifyUsers = new javax.swing.JButton();
        buttonHelp = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        buttonHome = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonLogout.setBackground(new java.awt.Color(254, 254, 254));
        buttonLogout.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        buttonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow-back-35.png"))); // NOI18N
        buttonLogout.setText("Logout ");
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(buttonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(852, 12, 120, 50));

        buttonVerifyUsers.setBackground(new java.awt.Color(174, 231, 248));
        buttonVerifyUsers.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        buttonVerifyUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/popupicon/correct.png"))); // NOI18N
        buttonVerifyUsers.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Verify Users", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        buttonVerifyUsers.setMaximumSize(new java.awt.Dimension(70, 86));
        buttonVerifyUsers.setMinimumSize(new java.awt.Dimension(70, 86));
        buttonVerifyUsers.setPreferredSize(new java.awt.Dimension(70, 86));
        buttonVerifyUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerifyUsersActionPerformed(evt);
            }
        });
        getContentPane().add(buttonVerifyUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, -1));

        buttonHelp.setBackground(new java.awt.Color(207, 255, 246));
        buttonHelp.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        buttonHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help-60.png"))); // NOI18N
        buttonHelp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Help", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        buttonHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHelpActionPerformed(evt);
            }
        });
        getContentPane().add(buttonHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 200, -1));

        buttonExit.setBackground(new java.awt.Color(174, 231, 248));
        buttonExit.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        buttonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit-60.png"))); // NOI18N
        buttonExit.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Exit", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });
        getContentPane().add(buttonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 200, -1));

        buttonHome.setBackground(new java.awt.Color(254, 254, 254));
        buttonHome.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        buttonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home-outline.png"))); // NOI18N
        buttonHome.setText("Home");
        buttonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHomeActionPerformed(evt);
            }
        });
        getContentPane().add(buttonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 12, 110, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Email", "Phone", "Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 820, 530));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manage-bg.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVerifyUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerifyUsersActionPerformed
        // TODO add your handling code here:
        verifyAndUpdateUserStatus();
    }//GEN-LAST:event_buttonVerifyUsersActionPerformed

    private void buttonHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHelpActionPerformed
        // TODO add your handling code here:
        showHelpDialog();
    }//GEN-LAST:event_buttonHelpActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Select", JOptionPane.YES_NO_OPTION);

        // If the user clicked "Yes" (a == 0), exit the application
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_buttonExitActionPerformed

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        // TODO add your handling code here:
        // Hide the current window (Home)
        this.setVisible(false);

        // Create a new instance of LoginAccountPage and show it
        new LoginAccountPage().setVisible(true);
    }//GEN-LAST:event_buttonLogoutActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        getAllRecords("");
    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String email = model.getValueAt(index, 2).toString();
        String status = model.getValueAt(index, 4).toString();
        if (status.equals("true")) {
            status = "false";
        } else {
            status = "true";
        }
        int a = JOptionPane.showConfirmDialog(null, "Do you want to change status of " + email + "", "Select ", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            userDAO.changeStatus(email, status);
            setVisible(false);
            new ManageUsers().setVisible(true);

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void buttonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHomeActionPerformed
        // TODO add your handling code here:
        // Create an instance of Home and make it visible
        Home homeFrame = new Home();
        homeFrame.setVisible(true);

        // Optional: Close the current frame if needed
        this.dispose();
    }//GEN-LAST:event_buttonHomeActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ManageUsers().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonHelp;
    private javax.swing.JButton buttonHome;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonVerifyUsers;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
